<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <AssemblyTitle>FluentStorage</AssemblyTitle>
      <TargetFrameworks>netstandard2.0;netstandard2.1;net70;net80;net90</TargetFrameworks>
      <AssemblyName>FluentStorage</AssemblyName>
      <PackageId>FluentStorage</PackageId>
      <Description>A polycloud .NET cloud storage abstraction layer. Provides a single unified polycloud API across 15+ clouds for Object manipulation, File uploads/downloads, File streaming/seeking, Object metadata, Versioning, Tags, Storage tier/class, Presigned URLs, Directory manipulation and more.</Description>
      <Copyright>Copyright (c) 2023 Robin Rodricks and FluentStorage Contributors</Copyright>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <PackageIcon>logo-nuget.png</PackageIcon>
      <Authors>Robin Rodricks, FluentStorage Contributors</Authors>
      <Version>8.0.21</Version>
      <PackageProjectUrl>https://github.com/robinrodricks/FluentStorage</PackageProjectUrl>
      <RepositoryUrl>https://github.com/robinrodricks/FluentStorage</RepositoryUrl>
      <RepositoryType>GitHub</RepositoryType>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <LangVersion>latest</LangVersion>
      <SignAssembly>True</SignAssembly>
      <AssemblyOriginatorKeyFile>sn.snk</AssemblyOriginatorKeyFile>
      <DocumentationFile>$(SolutionDir)build\FluentStorage.xml</DocumentationFile>
      <BaseOutputPath>$(SolutionDir)build\</BaseOutputPath>
      <WarningsAsErrors>CS0114;CS0507</WarningsAsErrors>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)' == 'Release'">
      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
      <DefineConstants>JSON</DefineConstants>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
      <DefineConstants>JSON</DefineConstants>
   </PropertyGroup>
   <ItemGroup>
      <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
      <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.0.15" />
   </ItemGroup>

   <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'netstandard2.1' ">
      <PackageReference Include="System.Text.Json" Version="8.0.6" />
      <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
   </ItemGroup>

   <ItemGroup>
      <None Include="..\.github\logo-nuget.png">
         <Pack>True</Pack>
         <PackagePath></PackagePath>
      </None>
   </ItemGroup>

</Project>
