<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <TargetFrameworks>netstandard2.0;netstandard2.1;net70;net80;net90</TargetFrameworks>
      <PackageId>FluentStorage.Azure.Blobs</PackageId>
      <RootNamespace>FluentStorage.Azure.Blobs</RootNamespace>
      <AssemblyName>FluentStorage.Azure.Blobs</AssemblyName>
      <Description>Extension to FluentStorage providing Azure blob storage.</Description>
      <Copyright>Copyright (c) 2023 Robin Rodricks and FluentStorage Contributors</Copyright>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <PackageIcon>logo-nuget.png</PackageIcon>
      <Authors>Robin Rodricks, FluentStorage Contributors</Authors>
      <Version>8.0.21</Version>
      <PackageProjectUrl>https://github.com/robinrodricks/FluentStorage</PackageProjectUrl>
      <RepositoryUrl>https://github.com/robinrodricks/FluentStorage</RepositoryUrl>
      <RepositoryType>GitHub</RepositoryType>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <LangVersion>latest</LangVersion>
      <SignAssembly>True</SignAssembly>
      <AssemblyOriginatorKeyFile>..\FluentStorage\sn.snk</AssemblyOriginatorKeyFile>
      <DocumentationFile>$(SolutionDir)build\FluentStorage.Azure.Blobs.xml</DocumentationFile>
      <BaseOutputPath>$(SolutionDir)build\</BaseOutputPath>
      <WarningsAsErrors>CS0114;CS0507</WarningsAsErrors>
   </PropertyGroup>

   <PropertyGroup Condition="'$(Configuration)' == 'Release'">
      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
   </PropertyGroup>


   <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.20.0" />
       <PackageReference Include="MimeMapping" Version="4.0.0" />
   </ItemGroup>
  
   <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'netstandard2.1' ">
      <PackageReference Include="System.Text.Json" Version="8.0.6" />
   </ItemGroup>

   <ItemGroup>
      <ProjectReference Include="..\FluentStorage.Azure\FluentStorage.Azure.csproj" />
      <ProjectReference Include="..\FluentStorage\FluentStorage.csproj" />
   </ItemGroup>

   <ItemGroup>
      <None Include="..\.github\logo-nuget.png">
         <Pack>True</Pack>
         <PackagePath></PackagePath>
      </None>
   </ItemGroup>

</Project>
