<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <TargetFrameworks>netstandard2.0;netstandard2.1;net70;net80;net90</TargetFrameworks>
      <Description>Extension to FluentStorage providing integration with Azure Key vault as blob storage.</Description>
      <FileVersion>1.0.0.0</FileVersion>
      <AssemblyVersion>1.0.0.0</AssemblyVersion>
      <PackageLicense>https://github.com/aloneguid/storage/blob/master/LICENSE</PackageLicense>
      <PackageId>FluentStorage.Azure.KeyVault</PackageId>
      <AssemblyName>FluentStorage.Azure.KeyVault</AssemblyName>
      <RootNamespace>FluentStorage.Azure.KeyVault</RootNamespace>
      <Copyright>Copyright (c) 2023 Robin Rodricks and FluentStorage Contributors</Copyright>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <PackageIcon>logo-nuget.png</PackageIcon>
      <Authors>Robin Rodricks, FluentStorage Contributors</Authors>
       <Version>8.0.21</Version>
      <PackageProjectUrl>https://github.com/robinrodricks/FluentStorage</PackageProjectUrl>
      <RepositoryUrl>https://github.com/robinrodricks/FluentStorage</RepositoryUrl>
      <RepositoryType>GitHub</RepositoryType>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <LangVersion>latest</LangVersion>
      <SignAssembly>True</SignAssembly>
      <AssemblyOriginatorKeyFile>..\FluentStorage\sn.snk</AssemblyOriginatorKeyFile>
      <DocumentationFile>$(SolutionDir)build\FluentStorage.Azure.KeyVault.xml</DocumentationFile>
      <BaseOutputPath>$(SolutionDir)build\</BaseOutputPath>
      <WarningsAsErrors>CS0114;CS0507</WarningsAsErrors>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)' == 'Release'">
      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
   </PropertyGroup>
   <ItemGroup>
      <PackageReference Include="Azure.Identity" Version="1.11.4" />
      <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.6.0" />
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\FluentStorage\FluentStorage.csproj" />
   </ItemGroup>

   <ItemGroup>
      <None Include="..\.github\logo-nuget.png">
         <Pack>True</Pack>
         <PackagePath></PackagePath>
      </None>
   </ItemGroup>

</Project>